const MenuApi = [
  {
    id: 1,
    image: "asdasd",
    name: "maggie",
    category: "lunch",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 2,
    image: "asdasd",
    name: "evening",
    category: "lunch",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 3,
    image: "asdasd",
    name: "tikka",
    category: "dinner",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 4,
    image: "asdasd",
    name: "jalebi",
    category: "breakfast",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 5,
    image: "asdasd",
    name: "parathe",
    category: "breakfast",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 6,
    image: "asdasd",
    name: "pakore",
    category: "dinner",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 7,
    image: "asdasd",
    name: "allu",
    category: "lunch",
    price: 25,
    description: "lorem askdljas asndklas",
  },
];
export default MenuApi;
