const MenuApi = [
  {
    id: 1,
    image: "https://source.unsplash.com/800x600/?noodles",
    name: "maggie",
    category: "lunch",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 2,
    image: "https://source.unsplash.com/800x600/?sandwich",
    name: "Sandwich",
    category: "lunch",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 3,
    image: "https://source.unsplash.com/800x600/?bbq",
    name: "tikka",
    category: "dinner",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 4,
    image: "https://source.unsplash.com/800x600/?jalebi",
    name: "jalebi",
    category: "breakfast",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 5,
    image: "https://source.unsplash.com/800x600/?juice",
    name: "Juice",
    category: "breakfast",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 6,
    image: "https://source.unsplash.com/800x600/?pulao",
    name: "Pulao",
    category: "dinner",
    price: 25,
    description: "lorem askdljas asndklas",
  },
  {
    id: 7,
    image: "https://source.unsplash.com/800x600/?samosa",
    name: "Samosa",
    category: "lunch",
    price: 25,
    description: "lorem askdljas asndklas",
  },
];
export default MenuApi;
